name: KBP
#Old name Kelsons-Plugin
main: me.Kelson.Commands
version: 1.0.3_45
description: This is the custom plugin for the kelsoncraft server!
author: kelson8
load: Startup

commands:
  kelson-help:
    description: This is the help for my plugin 
    permission: kelson.help
    permission-message: You do not have permission to use this command!

  tempfly:
    description: This is the tempfly command usage /tempfly <on, off>.
    permission: kelson.tempfly
    permission-message: You do not have permission to use this command!

  showxp:
    description: Shows the amount of xp the player has.

  location:
    description: Shows the location of the world your in.

  ipbans:
    description: Shows the ips that are banned in the server.
    permission: kelson.ipbans
    permission-message: You do not have permission to use this command!

  kheal:
    description: Heals the player heals another player if a name is specified.
    permission: kelson.heal
    permission-message: You do not have permission to use this command!

  kmotd:
    description: Shows the motd to the players from my plugin
    permission: kelson.kmotd
    permission-message: You do not have permission to use this command!

  setkmotd:
    description: Sets the message for /kmotd
    permisson: kelson.setkmotd
    permission-message: You do not have permission to use this command!

  kelson-reload: 
    description: This reloads the config.yml
    permission: kelson.reload
    permission-message: You do not have permission to use this command!
  
  serverinfo:
   description: Shows the server info to the player
   permission: kelson.serverinfo
   permission-message: You do not have permission to use this command!

  kelson:
   description: Help is seen with the use of this command

  playerinfo:
   description: Shows a players info
 
  kbp:
   description: This command is manley for testing atm
   
  whitelist:
   description: This command enables/disables the whitelist
   permission: kelson.whitelist
   permission-message: You do not have permission to use this command!
   usage: /whitelist <on/off>

permissions:
   kelson.playerinfo.others:
     description: Shows other players location
     default: op
     children:
         kelson.playerinfo: true
   kelson.*:
     description: Gives all permissions using kelsons plugin!
     default: op
     children:
         kelson.tempfly: true
         kelson.whitelist: true
         kelson.ipbans: true
         kelson.reload: true
         kelson.isop: true
         kelson.nofire: true
         kelson.heal: true
         kelson.nametag: true
         kelson.kmotd: true
         kelson.reload: true
         kelson.help: true
         kelson.configtest: true
         kelson.serverinfo: true
         kelson.location.others: true
         kelson.playerinfo.others: true
     
